[workspace]
members = [
	"crates/*",
	"examples/custom",
	"examples/layered",
	"examples/memory",
	"examples/postgres",
	"examples/redis",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nivek-ph/kape-rs"
homepage = "https://github.com/nivek-ph/kape-rs"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[workspace.dependencies]
# Internal dependencies
kape = { path = "crates/kape", version = "0.1.1" }
kape-memory = { path = "crates/kape-memory", version = "0.1.3" }
kape-postgres = { path = "crates/kape-postgres", version = "0.1.2" }
kape-redis = { path = "crates/kape-redis", version = "0.1.2" }
kape-testkit = { path = "crates/kape-testkit", version = "0.1.2" }

# External dependencies
async-trait = "0.1.92"
dotenv = { package = "dotenvy", version = "0.15.7" }
futures-lite = "2.6.1"
moka = { version = "0.12.16", default-features = false, features = ["future"] }
redis = { version = "1.2.2", default-features = false, features = [
	"connection-manager",
	"tokio-comp",
] }
sqlx = { version = "0.9.0", default-features = false, features = [
	"postgres",
	"runtime-tokio",
] }
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
