[package]
name = "kape-memory"
description = "In-memory backend adapter for Kape."
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.rs/kape-memory"
keywords = ["cache", "caching", "memory", "async"]
categories = ["caching", "asynchronous"]

[dependencies]
async-trait.workspace = true
kape.workspace = true
moka.workspace = true
thiserror.workspace = true

[dev-dependencies]
kape-testkit.workspace = true
tokio.workspace = true

[lints]
workspace = true
