[package]
name = "kape-postgres"
description = "PostgreSQL backend adapter for Kape."
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.rs/kape-postgres"
keywords = ["cache", "caching", "postgresql", "async"]
categories = ["caching", "asynchronous", "database"]

[features]
default = []
native-tls = ["sqlx/tls-native-tls"]
rustls = ["sqlx/tls-rustls-ring"]

[dependencies]
async-trait.workspace = true
kape.workspace = true
sqlx.workspace = true
thiserror.workspace = true

[dev-dependencies]
kape-testkit.workspace = true
tokio.workspace = true

[lints]
workspace = true
